name: GitHub Actions Build dnsmasq-china-list-smartdns
on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install curl git wget
    - name: Clone source code

      run: |
        git clone --depth=1 https://github.com/felixonmars/dnsmasq-china-list.git /opt/dnsmasq-china-list
        cd dnsmasq-china-list
        make raw

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: dnsmasq-china-list-smartdns
        path: /opt/dnsmasq-china-list/accelerated-domains.china.raw.txt
